"""ServiceUser title

Revision ID: 52b6c8317094
Revises: 57fea30b19ea
Create Date: 2015-08-01 17:58:37.464565

"""

# revision identifiers, used by Alembic.
revision = '52b6c8317094'
down_revision = '57fea30b19ea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_users', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_users', 'title')
    ### end Alembic commands ###
