# -*- coding: utf-8 -*-


AUTHORIZATION_GATEKEEPER = 'gatekeeper'
AUTHORIZATION_PERSON = 'person'
AUTHORIZATION_DEVICE = 'device'
AUTHORIZATION_ADMINISTRATOR = 'administrator'

PROVIDER_API_TOKEN = 2
PROVIDER_PASSWORD = 1
